#!/bin/bash

rm -r ~/.config/hypr/waybar/*
cp -r ~/.config/hypr/waybar-barcelona-b/* ~/.config/hypr/waybar/

#kill first
if [[ $(pidof waybar) ]]; then
	killall -q waybar
fi

while pgrep -u $UID -x waybar > /dev/null;do sleep 1;done

#startup again 
CONFIG="$HOME/.config/hypr/waybar/config.jsonc"
STYLE="$HOME/.config/hypr/waybar/style.css"
#/usr/bin/mpv ~/.config/hypr/waybar/f1.mp3 - sound of f1 engine when starting waybar

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
