#!/bin/sh

P10K_CONFIG_LIGHT="/home/just/p10k-dc.zsh"
P10K_CONFIG_DARK="/home/just/p10k-dc.zsh"

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
    P10K_CONFIG=$P10K_CONFIG_DARK
else
    SWITCHTO=""
    P10K_CONFIG=$P10K_CONFIG_LIGHT
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Arc-Dark$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Arc-Dark$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "Kora$SWITCHTO"

#change the background image and be cool about it ;)
#swww img ~/.config/hypr/wallpaper$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
~/.config/waybar/themes/DC/wallpaper-switcher ; /usr/bin/mpv ~/.config/waybar/blup2.mp3
#update the sddm image
#ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

# Set Powerlevel10k configuration
cp "$P10K_CONFIG" ~/.p10k.zsh



#restart the waybar
killall -SIGUSR2 waybar
#~/.config/hypr/alacritty-restart.sh

#pid=$(pgrep -x alacritty) && kill -SIGHUP "$pid"
#~/.config/waybar/scripts/alacritty-restart.sh
